import io
import sys
import contextlib

def execute_python_code(code: str) -> dict:
    """
    Executes a string of Python code generated by the agent.
    Captures console outputs (print statements) and runtime errors.
    """
    clean_code = code.strip()
    if clean_code.startswith("```python"):
        clean_code = clean_code[len("```python"):].strip()
    if clean_code.startswith("```"):
        clean_code = clean_code[len("```"):].strip()
    if clean_code.endswith("```"):
        clean_code = clean_code[:-3].strip()

    stdout_buffer = io.StringIO()

    try:
        with contextlib.redirect_stdout(stdout_buffer):
            exec(clean_code, globals())
        
        return {
            "status": "SUCCESS",
            "output": stdout_buffer.getvalue(),
            "error": None
        }
    except Exception as e:
        return {
            "status": "FAILED",
            "output": stdout_buffer.getvalue(),
            "error": f"{type(e).__name__}: {str(e)}"
        }